services:
  milkyano-api-production:
    image: aldovadev/milkyano-api:production
    container_name: milkyano-api-production
    restart: unless-stopped
    environment:
      - PORT=${PORT_MILKYANO}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS_MILKYANO}
      - DATABASE_URL=${DATABASE_URL_MILKYANO}
      - X_API_KEY=${X_API_KEY_MILKYANO}
    depends_on:
      - barber-db-production
    networks:
      - milkyano_default

  milkyano-db-production:
    container_name: milkyano-db-production
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER_MILKYANO}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_MILKYANO}
      - POSTGRES_DB=${POSTGRES_DB_MILKYANO}
    volumes:
      - milkyano-data:/var/lib/postgresql/data
    networks:
      - milkyano_default

volumes:
  milkyano-data:

networks:
  milkyano_default:
    external: true
