version: "3"

volumes:
  etc_wireguard:

services:
  wireguard:
    environment:
      - LANG=en
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${SECURE_WG_PASSWORD_HASH}
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
