version: "3"

networks:
  tunnel:
    external: true

volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik:
    image: traefik:v2.11.0
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /etc/traefik:/etc/traefik
      - traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - tunnel
